name: build-linux-x64
on: [push]

env:
  USE_CUDA: False
  BUILD_TEST: False

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        # os: [ubuntu-18.04,windows-2019,macos-10.15]
    
    steps:
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Clone pytorch/pytorch
      uses: actions/checkout@v1
      with:
        path: pytorch
        submodules: recursive

    - name: Add msbuild to PATH
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1.9.0

    - name: Setup Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.7

    - name: Create Build Environment
      with:
        path: pytorch
      run: cmake -E make_directory build
  
    - name: Configure CMake
      working-directory: pytorch/build
      run: |
        pwd
        ls 
        cmake -G Ninja -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_BUILD_TYPE:STRING=Release -DPYTHON_EXECUTABLE:PATH=`which python3` ..
        echo 'CMake Configure Ok'

    - name: Build pytorch binary
      working-directory: pytorch/build
      run: cmake --build . --target torch
